<?php
/**
 * Copyright © 2015 ShopGo. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php if ($this->isCacheAdditionalAllowed()): ?>
<div class="additional-cache-management">
    <h2>
        <span><?php /* @escapeNotVerified */ echo __('Additional Cache Management') ?></span>
    </h2>
    <p>
        <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanImagesUrl() ?>')" type="button">
            <?php /* @escapeNotVerified */ echo __('Flush Catalog Images Cache') ?>
        </button>
        <span><?php /* @escapeNotVerified */ echo __('Pregenerated product images files') ?></span>
    </p>
    <?php if ($block->isCleanMediaAllowed() && !$block->isInProductionMode()): ?>
    <p>
        <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanMediaUrl() ?>')" type="button">
            <?php /* @escapeNotVerified */ echo __('Flush JavaScript/CSS Cache') ?>
        </button>
        <span><?php /* @escapeNotVerified */ echo __('Themes JavaScript and CSS files combined to one file.') ?></span>
    </p>
    <?php endif; ?>
    <?php if ($block->isCleanStaticFilesAllowed() && !$block->isInProductionMode()): ?>
        <p>
            <button onclick="setLocation('<?php /* @escapeNotVerified */ echo $block->getCleanStaticFilesUrl() ?>')" type="button">
                <?php /* @escapeNotVerified */ echo __('Flush Static Files Cache') ?>
            </button>
            <span><?php /* @escapeNotVerified */ echo __('Preprocessed view files and static files') ?></span>
        </p>
    <?php endif; ?>
    <?php echo $block->getChildHtml(); ?>
</div>
<?php endif; ?>
